module.exports = {
	entry:['./src/js/index.jsx','./src/css/styles.scss'],
	output:{
		path:`${__dirname}/dist/js`,
		filename:'bundle.js'
	},
	watch:true,
	module:{
		rules:[
			{
				test:/\.js$/,
				exclude:/node_modules/,
				use:{
					loader:'babel-loader',
					options:{
						presets:['env'],
						plugins:['transform-object-rest-spread','transform-class-properties']
					}
				}
			},
			{
				test:/\.jsx$/,
				exclude:/node_modules/,
				use:{
					loader:'babel-loader',
					options:{
						presets:['react','env'],
						plugins:['transform-object-rest-spread','transform-class-properties']
					}
				}
			},
			{
				test:/\.scss$/,
				use:[
					'style-loader',
					{
						loader:'css-loader',
						options:{
							url:false
						}
					},
						'sass-loader'
				]
			},
			{
				test:/\.css$/,
				use:[
					'style-loader',
					{
						loader:'css-loader',
						options:{
							url:false
						}
					},
				]
			},

		]
	},
	devtool:'source-map',
	resolve:{extensions:['.js','.jsx']}
}
